milestone-07:update some file for milestone-07 and work on for images

diff --git a/milestone-07/api/api.yaml b/milestone-07/api/api.yaml
--- a/milestone-07/api/api.yaml
+++ b/milestone-07/api/api.yaml
@@ -2,7 +2,8 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: api-deployment
-  namespace: student-api
+  labels:
+    app: api
 spec:
   replicas: 1
   selector:
@@ -15,12 +16,56 @@ spec:
     spec:
       containers:
         - name: api-container
-          image: your-api-image
+          image: rajeshecb70/api:3.0.0 # Replace with your API container image
+          ports:
+            - containerPort: 5000
           env:
-            - name: API_KEY
+            - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
-                  name: db-api-secret
-                  key: MYSQL_PASSWORD # Assuming the same password or create a separate secret key for API_KEY if needed
+                  name: mysql-secret
+                  key: DATABASE_URL
+          #command: ["/bin/sh", "-c", "sleep 100"]
+          #command: ["python3", "-c", "flask run --host=0.0.0.0 --port=5000"]
+          #command: ["python3", "-m", "flask run --host=0.0.0.0 --port=5000"]
+
+      # Init Container that checks if the database is up and runs migrations
+      initContainers:
+        - name: db-migration
+          image: python:3.10-alpine # Using a Python Alpine image
+          command: [
+              "/bin/sh",
+              "-c",
+              "
+              #!/bin/sh
+              set -e  # Exit immediately if a command exits with a non-zero status
+              echo 'Checking if the MySQL database is up...'
+              while ! nc -z $DATABASE_URL 3306; do
+              echo 'Waiting for MySQL database...'
+              sleep 2  # Wait for 2 seconds before checking again
+              done
+              echo 'MySQL database is up! Running migrations...'
+              python3 -m flask db upgrade
+              ",
+            ]
+          env:
             - name: DATABASE_URL
-              value: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}"
+              valueFrom:
+                secretKeyRef:
+                  name: mysql-secret
+                  key: DATABASE_URL
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: api-service
+  labels:
+    app: api
+spec:
+  type: ClusterIP # This is the default type and is used for internal communication within the cluster.
+  ports:
+    - port: 5000 # The port that the service will expose
+      targetPort: 5000 # The port on the pod to forward traffic to
+      protocol: TCP # The protocol used
+  selector:
+    app: api # This selector will route traffic to the pods with this label
